destral/cli.py
destral/testing.py

Now we can use an existing database with the environment variable `OPENERP_DATABASE`.
**Note**: The module to test must be installed/updated before run the tests.
/cc @tinogis

Force database

---

destral/cli.py
destral/utils.py

Before if tests are defined but there is some error loading the
module the result was the same as it doesn't exist. But it must
fail because the tests written are not executed.

Improve module test detection

---

destral/cli.py
destral/testing.py
requirements-dev.txt
setup.py
spec/testing_spec.py

Add mamba support to destral
You can create `spec` tests adding a new directory to the root of the module with name `spec` and files with `_spec.py` to test
Closes #18

Add mamba support

---

destral/testing.py
requirements-dev.txt

Now modules are always installed, even if a database is defined

Improvement: Allways install Modules

---

destral/cli.py

Run mamba spec if folder `config['root_path']/spec` exists

Add the possibility to run spec server tests

---

destral/cli.py
destral/patch.py
spec/fixtures/__init__.py
spec/testing_spec.py
spec/utils_spec.py

When testing more than one module and one of them *patches* `report.interface.register_all` other modules can fail. With this every time a test of a module is finished the original `report.interface.register_all` function pointer is restored.

Fix patch register all

---

destral/testing.py

Always assign db_name to `result` test. Because if we use an existing database the `result` test object didn't have `db_name` attribute.

[FIX] Result DB Name

---

destral/cli.py
destral/cover.py
destral/utils.py
docs/README.rst
docs/api.rst
setup.py

Now is possible to **run destral with coverage** to know the lines executing during the test.
For now the system only includes the lines of the module. To run with coverage:
```sh
$ destral --enable-coverage -m module_to_test
```
Then you can see the report executing
```sh
$ coverage report
```

Enable coverage

---

destral/cli.py
destral/cover.py
docs/README.rst

Add an option to print the coverage report doing:
```sh
$ destral --report-coverage -m module_to_test
```

Add option to print the report coverage

---

destral/openerp.py

To avoid if more than one connection is used
in the pool template1 is used as a template to create the new
database.

Use postgres database

---

destral/cli.py

Move start coverage before load tests

Start coverage before load tests

---

destral/cli.py

If no modules will be test we run coverage on serve else on modules to test

Coverage server or modules

---

destral/utils.py
requirements-dev.txt

Fixed an error where the netsvc wouldn't be cleared after checking if a module exists.

Fix: Netsvc doesn't allways clear

---

destral/testing.py

Do not puts prefix `addons` on module loading to avoid problem when module is forced in class

IMP No addons in module loading

---

destral/cli.py

Pycharm in Windows passes additional arguments for debugging, and destral fails because click module is not configured to allow unknown or extra arguments.

Ignore unknown and extra arguments

---

destral/openerp.py
destral/testing.py

Before this patch, when using `no-dropdb` if we want to use the database with the client, we must update the `res_users` table setting a password for `admin` user.
With this patch the `admin` user is enabled with `admin` password.

If no-drodb is used enable admin user

---

destral/cli.py

With this option we can skip install requirements for every module.
Usually this is useful in local environments where we have all the requirements already installed.

Option to no install requirements

---

destral/openerp.py
destral/testing.py

Better enabled user admin:
- Only if it doesn't have password setted
- Search for active/no active
- Writes active:True
Log with the database name when not dropping

Better no dropdb

---

destral/patch.py
spec/patch_spec.py

Added a class to *patch* the cursor creation.
In the tests **no commit** is needed but when we make a new cursor the visibility from the other cursor is hiden, for thus we have patched the creation of new cursos and using the same cursor.
If we have to test some method that create a new cursor we can do the following:
```python
with Transaction().start(self.database) as txn:
cursor = txn.cursor
with PatchNewCursors(cursor):
db = pooler.get_db_only(cursor.dbname)
new_cursor = db.cursor()
expect(cursor).to(be(new_cursor)
```

Patch cursor to not commit, rollback or close

---

destral/patch.py

A missing import `sql_db` which doesn't restores the original `db_connect()` method

Fix missing import

---

destral/testing.py

Try to run tests from module, if not found (AttributeError exception) run from the "destral.testing" module (base testing module)

Add try-except for OOBaseTest call from parameter

---

destral/testing.py
destral/utils.py
spec/utils_spec.py

Closes #78
Add missing and untranslated strings list on log when test fails

[To Merge] Add missing strings pofiles

---

destral/testing.py

Pass a list of modules instead of a single module to translate method.
The single module was managed as a list of chars and pot file was wrongly generated. Passing a list of modules each element of the list is a module and the strings are generated correctly.
Solves https://github.com/gisce/destral/issues/80.

FIX: Generate pot file correctlly

---

destral/testing.py

Closes https://github.com/gisce/destral/issues/83
Changed the behaviour of the test in the case of some module not having translations. Instead of skipping the test, it will make the test fail.

Changed the return method of a tests in case of one module not having translations

---

destral/testing.py

Check report translations for each module using new method from [gisce/erp#4972](https://github.com/gisce/erp/pull/4972)
Report translatable strings are being lost due to wrong process of translations to fix module translations. 
→ Test Translations is making developers erase report translations
→ Including those strings, the translations won't be lost

Add Report Translations Check

---

destral/testing.py

If no environment `DESTRAL_TESTING_LANGS` is set, no execute any translation related test

No execute translationst tests if not environment

---

setup.py

Mamba has updated its version and it generates an error on our use of it. Setting the version to the 0.8.6 will fix the problem.

SET required mamba version to 0.8.6

---

destral/cli.py

When environment does not have the "CI_REPO" variable, it does fail to ask on GITHUB API.
Checking for the existance of this environ var before asking github, the test will run using the alternative way if no "CI_REPO" is set.

TO MERGE: ADD "CI_REPO" check before asking github

---

destral/cli.py

Adds a parsing to the environment var "`CI_PULL_REQUEST`" for the CI builds that add the full PR URL instead of the Number.

TO MERGE: ADD "CI_PULL_REQUEST" env var parse to get PR number

---

destral/cli.py

Failin when no PR is set as it tries to parse the "CI_PULL_REQUEST" but it's not set yet

Remove Exception type to catch all exceptions

---

destral/testing.py

Suport to run mamba if a `specs` directory is found

Support for specs dir

---

destral/cli.py
destral/junitxml_testing.py
destral/testing.py
setup.py

Closes #96 
Adds:
→ Maybe we can export it to an open source repository for the community?

Add export junitxml

---

destral/cli.py
destral/junitxml_testing.py

Without marking TestCases as Error/Failures/Skipped, the TestSuit does not count them as errors.
This makes the CircleCI unable to show the errors if any

TO MERGE: Add error, failure and skipped states on testsuite

---

destral/junitxml_testing.py

Add missing super calls to correctly register results. Even though it registered the result on the JunitXML's Result class.
- Output on tests results wasn't submitted and/or registered for Destral's call
Affected results were:
- Failure
- Skip
- Success

Add super calls to correctly register results

---

destral/openerp.py
setup.py

If a db name is provided and it does not exist, create such database and populate it.
This feature enables a more agile workflow when developing. Just pick the same name (ie, testdb) for the database. The first test run it will be created, the next ones you will reuse it. If you need a rebuild because you changed data or data structure, just run 'dropdb testdb' and it will be rebuild on the next test run.
Existing workflow created a random name, although convenient for CI, while developing, you had to figure out the generated name and then set as envvar. Each time you need to rebuild the database, such name changes and you have to set it over and over.

if named db not found, it creates it

---

destral/openerp.py

Before drop database try to close open connections to solve test problems like above example
``` bash
INFO:destral.openerp:Droping database test_1530099807
Traceback (most recent call last):
File "/home/circleci/src/venv/bin/destral", line 11, in <module>
sys.exit(destral())
File "/home/circleci/src/venv/lib/python2.7/site-packages/click/core.py", line 722, in __call__
return self.main(*args, **kwargs)
File "/home/circleci/src/venv/lib/python2.7/site-packages/click/core.py", line 697, in main
rv = self.invoke(ctx)
File "/home/circleci/src/venv/lib/python2.7/site-packages/click/core.py", line 895, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/home/circleci/src/venv/lib/python2.7/site-packages/click/core.py", line 535, in invoke
return callback(*args, **kwargs)
File …
```

Terminate connections form database before dropdb

---

destral/testing.py
docs/README.rst
docs/how-to.rst
docs/index.rst

Add a new class which automatically have `setUp` and `tearDown` to have a transaction in every test:
```python
def setUp(self):
self.txn = Transaction().start(self.database)
self.cursor = self.txn.cursor()
self.uid = self.txn.user
def tearDown(self):
self.txn.stop()
```
We also add some documentation

Add new class OOTestWithCursor

---

destral/testing.py

Getting the cursor from the transaction fails as it's a property and not a method.
Getting it without parenthesis should fix the problem

Fix cursor getting on OOTestCaseWithCursor

---

destral/cli.py
destral/testing.py

Added a new option `--all-tests`  / `-a` which will run all the tests of the dependencies and the tests of the module itself.

Allow to run all the tests

---

destral/utils.py

This will improve the detection of a bad typed module name as the comma mark the real form of the module name set on TERP. 
For an example, if you add an extra space after a module name on TERP, this will help to detect that the deps. is bad typed.

Improve error message for module not found

---

destral/cli.py
destral/linter.py
setup.py

Instead of #62 which runs the pylint we integrated it as a library.
It will use the `.pylintrc` file if is found
Closes #62

Add Pylint support

---

destral/utils.py

Hemos encontrado un caso donde la recursión de búsqueda de dependencias se hace infinita. Con este *fix* se soluciona que solo añade si los módulos no están ya en la lista de dependencias

Sólo añadir dependencias si no están en la lista

---

destral/cli.py

Fix support for working urllib in both py2 and py3.
In python3 `Request` use `urllib.request.Request`, in python 2.x use directly `urllib.Request`

Fix import urllib working with py2 and py3

---

destral/cli.py

```python
>>> import subprocess
>>> type(subprocess.check_output(["git", "diff", "--name-only", "HEAD~1..HEAD"]))
<type 'str'>
```
```python
>>> import subprocess
>>> type(subprocess.check_output(["git", "diff", "--name-only", "HEAD~1..HEAD"]))
<class 'bytes'>
```

Subprocess compatibility py2 & py3

---

destral/cli.py

Now is possible to call destral with `--database=database_name` and it's the same as exporting `OPENERP_DB_NAME` environment var

Allow to pass database as argument

---

destral/transaction.py

To avoid tests failing due when creating a cursor the `user_obj.get_context()` is called, all cursors are marked as executed and tests transactions are failing

Disable DB_CURSOR_EXECUTE on create cursor

---

destral/patch.py

Al testear metodos con el cursor parcheado y que los cursores internos se contruieran con parametros extra como el nivel de isolación o readonly lanzava un error ya que no estava adaptado para permitirlos
https://github.com/gisce/erp/pull/14977

Evitar que lanze errores de parametros al usar PatchNewCursors con metodos que tengan cursores con parametros

---

destral/cli.py
destral/openerp.py

Kill threads before exiting, this was found when the pubsub thread was introduced https://github.com/gisce/erp/pull/15492

Calling signal SHUTDOWN_REQUEST before exiting

---

destral/cli.py
destral/openerp.py

- Se quedaba atorado cuando fallaba la instalación de algun modulo (no mataba el main)
- Interrumpe la ejecucion y lanza el shutdown

Fix thread infinito

---

.bumpversion.cfg
.github/workflows/release.yml
.github/workflows/version.yml
destral/cli.py

if OPENERP_DESTRAL_MODE is set it up, we now erp is running from destral, then we can raise some specific errors or change behavior.
For example we can raise errors on tests that on the contrary would only be logged in.
```diff
diff --git a/server/bin/osv/orm.py b/server/bin/osv/orm.py
index 8272d594f7a..84f55853754 100644
--- a/server/bin/osv/orm.py
+++ b/server/bin/osv/orm.py
@@ -238,6 +238,11 @@ class browse_record(object):
else:
logger = netsvc.Logger()
logger.notifyChannel('orm', netsvc.LOG_ERROR, "Programming error: field '%s' does not exist in object '%s' !" % (name, self._table._name))
+                import os
+                if int(os.environ.get('OPENERP_DESTRAL_MODE', "0")):
+                    raise AttributeError(
+                        "Programming error: field '%s' …
```

Add env var to know if erp is running from destral

---

destral/testing.py

Allow to define classes with `_test_class` attribute to disable check access rules for this models
```python
class GiscedataComercialComissioTest(osv.osv):
_name = 'giscedata.comercial.comissio'
_test_class = True
```

Dont check acces rules for classes with attribute _test_class True

---

destral/patch.py

Poder usar PatchNewCursors con codigo que crea y usa nuevos cursores con el `with`
```python
class TestPatchedCursors(testing.OOTestCase):
def test_multiple_contexts(self):
def magic(cursor, uid):
import pooler
with pooler.get_db_only(self.database).cursor() as _cr:
pass
user_obj = self.openerp.pool.get('res.users')
setattr(user_obj, 'magic', magic)
with Transaction().start(self.database) as txn:
cursor = txn.cursor
uid = txn.user
with PatchNewCursors():
user_obj.magic(cursor, uid)
```
```
2023-11-24 09:13:59,280:INFO:destral.testing.results:Traceback (most recent call last):
File "/home/psala/Projects/erp/server/bin/addons/base/tests/__init__.py", line 47, in test_multiple_contexts
user_obj.magic(cursor, uid)
File "/home/psala/Projects/erp/server/bin/addons/base/tests/__init__.py", line …
```

Fix PatchNewCursor if created cursors use context __enter__ /__exit__

---

destral/testing.py

Se ha detectado un caso particular en que el test `test_all_views` pasaba, aun sin existir el campo en el modelo indicado en la posicion de la flecha.
(estava definido en otro modelo)
- Salta el test para las inher views
Estare unos dias testeando cambios aprobechando cuando tenga que pasar tests

Testear inher views in free time

---

destral/cli.py

El programa se congelaba cuando fallava la carga de la bateria de tests, cuando detecta un problema con dicha carga, ahora finaliza el programa con exit code 1
Antes:
Ahora:

BugFix: Dont freeze program on suite load error

---

setup.py

- Hay que controlar la versión del paquete `mamba` para asegurar la compatibilidad tanto en Python 2 como en Python 3
- https://github.com/gisce/erp/pull/19901

Controlar versión de `mamba` para asegurar compatibilidad con Python2 y Python3

---

destral/testing.py

```
2024-07-03 15:31:22,027:INFO:destral.testing.results:ERROR: test_all_views (destral.testing.OOBaseTests)
Tests all views defined in the module.
2024-07-03 15:31:22,027:INFO:destral.testing.results:
2024-07-03 15:31:22,027:INFO:destral.testing.results:----------------------------------------------------------------------
2024-07-03 15:31:22,027:INFO:destral.testing.results:
2024-07-03 15:31:22,027:INFO:destral.testing.results:Traceback (most recent call last):
File "/home/psala/Projects/destral/destral/testing.py", line 159, in test_all_views
model.fields_view_get(txn.cursor, txn.user, view.id, view.type, version=view.version)
File "/home/psala/Projects/erp/server/bin/addons/custom_search/custom_search.py", line 418, in fields_view_get
view_id, view_type, context, toolbar, version) …
```

Skip View validation for redefined and controlled fields_get

---

destral/cli.py

Introduce new option `--coverage-html-report "path/to"` to directly generate report html without manual step

New option to html  coverage report directly

---

destral/openerp.py
destral/testing.py

With the addition of the test_depends key in __terp__ files, the necessary modules are now pre-installed to run the tests efficiently.
```py
"test_depends": [
"giscedata_tarifas_cargos_20210601",
"giscedata_tarifas_peajes_20160101",
"giscedata_tarifas_peajes_20170101",
"giscedata_tarifas_peajes_20180101",
"giscedata_tarifas_peajes_20190101",
"giscedata_tarifas_peajes_20200101",
"giscedata_tarifas_peajes_20210601",
"giscedata_tarifas_peajes_20220101",
"giscedata_tarifas_pagos_capacidad_20170101",
"giscedata_tarifas_pagos_capacidad_20190101",
"giscedata_tarifas_pagos_capacidad_20210601"
],
```
This approach avoids redundant dependency installations during test execution, thus accelerating the runs by ensuring all modules are already available. This change centralizes dependency management, …

Allow extra module dependencies to be installed on tests

---

destral/openerp.py
destral/transaction.py

Since https://github.com/gisce/erp/pull/21260, all ORM objects include a new attribute, api, with a db attribute. However, it was only available in "running" mode, not in "destral" mode, due to its dependency on the web service.
With this change, it is now also available in "destral" mode.

Simulate webservice call and make api and api.db aviable on objects under testing context

---

destral/testing.py

This pull request updates the `destral/testing.py` file to integrate web service context management into the test setup and teardown process. The changes ensure that a `WebserviceBase` instance is pushed to and popped from the `_ws_info` context stack during the test lifecycle.
* **Imports added for context management**: Added imports for `_ws_info` from `ctx` and `WebserviceBase` from `tools.service_utils` to support the new web service context management functionality.
* **Test lifecycle updates**:
- In `setUp(self)`: Added a line to push a `WebserviceBase` instance (initialized with `uid`) to the `_ws_info` context stack, ensuring the web service context is available during tests.
- In `tearDown(self)`: Added a line to pop the `_ws_info` context stack, cleaning up the web service …

Add ws_info to context in tests

---

destral/patch.py

This pull request introduces enhancements to the `destral/patch.py` file, focusing on improving the patching mechanism for database connections. The changes include adding new imports, refactoring the patching logic, and enabling the patching functionality to be used as a decorator.
* **New imports added**: Introduced `current_session` and `current_cursor` from `ctx` to manage the current database session and cursor during patching.
* **Refactored patching logic**: 
- Added `patch` and `unpatch` methods to encapsulate the logic for modifying and restoring database connection behavior. 
- Updated `__enter__` and `__exit__` methods to use the new patching methods, improving readability and maintainability.
* **Decorator functionality**: Added a `__call__` method to allow the patching …

Allow use PatchNewCursors as a decorator
