gisce/destral

- destral/openerp.py
> Testing to patch _poolJobs from ir.cron

- destral/testing.py
Let other tests cases patch the install process
> Split install_module into a function

- destral/testing.py
> Create database per class and not per test

- destral/testing.py
> Check all models have access rules defined

- destral/testing.py
> Use custom TestSuite to create database for suite

- destral/cli.py
By error I've local commented this line and pushed in the release cycle.
> Fix commented line error

- destral/testing.py
- destral/utils.py
> Fix translation testing

- destral/testing.py
- destral/utils.py
- setup.py
- spec/fixtures/pofileA.po
Remove duplicated code reading a `*.po file`
> Refactoring. Add method to read_po

- destral/testing.py
- setup.py
Adapt arguments to new version of mamba
Closes #89
> Add new arguments to Mamba

- destral/utils.py
Support for some extra requirements during the module tests using `requirements-dev.txt`
As example of https://github.com/gisce/erp/pull/5623
> Support for requirements-dev.txt

- destral/testing.py
> Fix call `runner()` instead of `create_runner()`

- destral/junitxml_testing.py
- setup.py
Fix the Mamba's ApplicationFactory for the updated MAMBA API called from the fix on PR #104
> Improve/Fix JunitXML for Mamba ApplicationFactory with the new API

- destral/openerp.py
Before to do all the code to install the module, check if it is already installed. If it is installed, then don't do anything.
It speeds up the process about 45%
/cc @rchamorro 
Fixes #108
> Check if the module is already intalled

- destral/__init__.py
- destral/cli.py
- destral/utils.py
- setup.py
Support for working in both py2 and py3
> Working with py2 and py3

- destral/testing.py
> Import StringIO (python3)

- destral/cli.py
- destral/testing.py
- destral/transaction.py
- destral/utils.py
- setup.py
> Decode urllib response

- destral/testing.py
Testegem mirant si hi ha diferents versions de la vista
> Testegem mirant si hi ha diferents versions de la vista

- destral/openerp.py
Load monkeypatches before tools imports - Py3 compat
> Add import service, pre load erp monkeypatches

- setup.py
pylint removed a lot of functions in 3.0
> Fix pylint version

- destral/cli.py
Force execution of base tests if only core is touched
> Force to execute base module tests for core changes

- destral/cli.py
Al detectar cambios a través de patch, podia detectar mas ficheros modificados de los que realmente habia si se han desecho cambios
> Change api request to diff
